alias ..='cd ..'
alias ...='cd ../..'
alias blog='cd ~/repos/personal-website/src/posts'
alias bug='gh issue create -a @me -l bug -t' # e.g. bug "Thing X is broken when I do Y"
alias chatgpt='docker run -v /home/jack/chatgpt/data/:/app/data -p 3000:3000 ghcr.io/cogentapps/chat-with-gpt:release'
alias dk='docker'
alias dkc='docker-compose'
alias dotfiles='cd ~/repos/dotfiles'
alias down='cd ~/Downloads'
alias du='ncdu'
alias gcp_access_token='gcloud auth print-access-token'
alias gcp_id_token='gcloud auth print-identity-token'
alias gg='gitg'
alias gk='gitk --all'
alias gla='git config --get-regexp alias'
alias grep='grep --color=auto'
alias issue='gh issue create -a @me -l enhancement -t' # e.g. issue "Issue title here"
alias issues='gh issue list'
alias l='lsd --oneline' # ls -C
alias lg='lazygit'
alias ll='lsd --all --long --oneline' # ls -alF
alias loc='cloc --progress=1 --vcs git' # or cloc --progress=1 --vcs git --by-file
alias ls='ls -l --human-readable --color=auto --group-directories-first'
alias myip='curl http://ipecho.net/plain; echo'
alias notes='cd ~/Dropbox/notes && lsd --oneline'
alias packages='sudo apt list --installed | less'
alias pk='pkill --signal SIGTERM --echo --count' # e.g. pkill tmux
alias repl='rlwrap bb --repl'
alias repos='cd ~/repos'
alias rm='trash'
alias sa='sudo apt'
alias skopeo='docker run --rm quay.io/skopeo/stable'
alias snaps='snap list'
alias snippets='cd ~/Dropbox/snippets'
alias syslog='sudo tail -100f /var/log/syslog'
alias vi='nvim'
alias vim='nvim'
alias t2='tree -L 2 -I node_modules'
alias t3='tree -L 3 -I node_modules'
alias webify="mogrify -resize 690\> *.png"
alias webserver='python3 -m http.server 8090'
alias wget='wget --continue'
alias ytd='yt-dlp --ignore-errors'
alias ytmp3='yt-dlp --ignore-errors --extract-audio --audio-format mp3' # download only audio, in mp3 format
